### ISSUE TITLE
Compilation with clang fails on OS X (error: ambiguous call to std::abs())

### ISSUE THREAD

**Issue by egparedes** [sgorsten/linalg#7]
I found this problem trying to compile the tests with clang (Apple LLVM version 8.0.0 / clang-800.0.42.1) on my OS 10.11.6 workstation. The compilation with GNU g++ works ok on the same machine.

I could fix it on my machine by including <cstdlib> as commented here:

 http://stackoverflow.com/questions/30084577/ambiguous-call-to-abs

Thanks for the library.

**Comment by sgorsten** [comment]
Thanks for identifying this issue, and for your interest in this library.

Fixed as of 539f659496f4490972b812f1a2d769589894ae51.
